### ISSUE TITLE
is publicAddr node a single point of failure?

### ISSUE THREAD

**Issue by didip** [lithdew/flatend#9]
I am currently following along the chat example and I don't quite understand 1 thing.

Is publicAddr node a single point of failure? Does publicAddr act like an elected master?

**Comment by lithdew** [comment]
Hello!

Nodes with a public address are just nodes that may publicly be directly connected to (you may have nodes that are anonymous which would only provide services they choose to connect to).

Typically, for a node to join a network, they need to know at least one of the other nodes addresses in the network (which we usually label as a bootstrap node).

A bootstrapping process then happens where the node that joins the network would ask the bootstrap node what other nodes exist in the network, and connect to them too.

The difference between this and centralized service discovery is that you can have any node/peer act as a bootstrap node, vs only being able to connect to just one centralized service discovery node. Hence, service discovery may happen with there being no single point of failure or elected master.

For more information, this process is labelled in the Kademlia protocol specification as the FIND_NODE RPC call.

Hope this helps!

**Comment by didip** [comment]
Gotcha. Thanks for explaining.
